### ISSUE TITLE
Can't seem to access map or view instances after updating component with data

### ISSUE THREAD

**Issue by Chonguis** [tomwayson/esri-loader-react-starter-kit#2]
code link https://gist.github.com/Chonguis/348ac0914c86bf5da8fb24da7d9383a2

Hello Tom. I've been playing with react for about a month now but have worked with the arcgis js api for almost a year. I'm having a problem trying to update the map or view instances once I pass data to the esriComponent. Let's say I'm passing a data object with coordinates. The initial state of the esriMapComponent has a default view on brooklyn. The user then submits a search that makes a ajax request to an API and this API responds with coordinates. Once I have this data object, I return the esriMapComponent passing in data as props. In this, I am succesfull and doing a simple log on the render method will indicate that data indeed was passed on. The problem is that since the esri modules are loaded in the componentDidMount lifecycle hook, nothing seems to run again. I then want to go to view.goTo(coordinates) but I'm having trouble because if I put a console log inside of this lifecycle hook, it won't run again when the component is updated by passing the data from parent component (Map route). 

My questions are: Is there another place where I could have access to the view, map, scenelayer instances that are not enclosed in this lifecycle hook? Is this problem specific to this library (react starter kit with esri-loader). Can you recomend a way to achieve what I want to do using the loader maybe in another way?

Hope example is clear and that this can be fixed (crossing fingers). Hope you have a great day!

**Comment by Chonguis** [comment]
<script src="https://gist.github.com/Chonguis/348ac0914c86bf5da8fb24da7d9383a2.js"></script>

**Comment by tomwayson** [comment]
I've responded in https://github.com/Esri/esri-loader/issues/91 since there's more of a conversation going on over there.

**Comment by tomwayson** [comment]
closing this as it was resolved in above linked issue.
